services:
  django:
    build: .
    container_name: ibm-django

    working_dir: /app

    volumes:
      - ./app:/app

    ports:
      - "8000:8000"

    tty: true

  postgres:
    image: postgres:16

    container_name: ibm-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: